name: Build Windows Exe

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install pyinstaller
    - name: Build exe
      run: pyinstaller --name myapp --onefile --windowed --hidden-import=openpyxl --hidden-import=requests --hidden-import=docx --hidden-import=configparser --hidden-import=PyQt5 --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui gui.py program_opt.py


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myscript.exe
        path: .
